cms/urls.py
from django.conf.urls import url
from cms import views


urlpatterns = [
    url(r'^paper/$', views.paper_list, name='paper_list'),
    url(r'^paper/add/$', views.paper_edit, name='paper_add'),
    url(r'^paper/mod/(?P<paper_id>\d+)/$', views.paper_edit, name='paper_mod'),
    url(r'^paper/del/(?P<paper_id>\d+)/$', views.paper_del, name='paper_del'),
    url(r'^report/(?P<paper_id>\d+)/$', views.ReportList.as_view(),  name='report_list'),
    url(r'^report/add/(?P<paper_id>\d+)/$', views.report_edit, name='report_add'),
    url(r'^report/mod/(?P<paper_id>\d+)/(?P<report_id>\d+)/$', views.report_edit, name='report_mod'),
    url(r'^report/del/(?P<paper_id>\d+)/(?P<report_id>\d+)/$', views.report_del, name='report_del'),
    url(r'^admin_message/$', views.admin_message, name='admin_message')
]

paperintro/urls.py
from django.conf.urls import url, include   # ←, includeを追加
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cms/', include('cms.urls', namespace='cms')),   # ←ここを追加
]

cms/models.py
from django.db import models
from django.utils import timezone

class Paper(models.Model):
    title = models.CharField('Title', max_length=1023)
    authors = models.CharField('Authors', max_length=1023, blank=True)
    references = models.CharField('References', max_length=1023, blank=True)
    pages = models.CharField('Pages', blank=True, max_length=255)
    year = models.IntegerField('Year',blank=True, default = 0)
    URL = models.CharField('URL', max_length=1023, blank=True)
    abstract = models.TextField('Abstract', blank=True)
    reading = models.CharField('Reading',blank=True, max_length=255)
    note = models.CharField('Note',blank=True, max_length=255)
    def __str__(self):
        return self.title

class Report(models.Model):
    paper = models.ForeignKey(Paper,verbose_name='Paper',related_name='reports')
    reporter = models.CharField('Reporter', max_length=255)
    grade = models.CharField('Grade', max_length=32, blank=True)
    date = models.DateField(default=timezone.now)
    motivations = models.TextField('Motivations', blank=True)
    contributions = models.TextField('Contributions', blank=True)
    questions = models.TextField('Questions and Future works', blank=True)
    def __str__(self):
        return self.motivations

cms/forms.py
from django.forms import ModelForm
from cms.models import Paper, Report
from datetimewidget.widgets import DateWidget

class PaperForm(ModelForm):
    class Meta:
        model = Paper
        fields = ('title', 'authors', 'references', 'pages',
                  'year', 'URL', 'abstract', 'reading', 'note',)


class ReportForm(ModelForm):
    class Meta:
        model = Report
        fields = ('reporter', 'grade', 'date', 'motivations',
                  'contributions', 'questions', )
        widgets = {
            'date': DateWidget(usel10n=True)
        }


'''
class ToggleForm(ModelForm):
    class Meta:
        model = Paper
        fields = ('recommended',)
'''

cms/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views.generic.list import ListView

from cms.models import Paper, Report
from cms.forms import PaperForm, ReportForm
import datetime


def gakunen_subtraction(today,prev):
    if today.month < 4:
        today_year = today.year - 1
    else:
        today_year = today.year
    if prev.month < 4:
        prev_year = prev.year - 1
    else:
        prev_year = prev.year
    return today_year - prev_year
    

def paper_list(request):
    url = request.build_absolute_uri()
    if '?' in url:
        params_list = [x.split('=') for x in url.split('?')[-1].split('&')]
    else:
        params_list = []
    params = {}
    for param in params_list:
        params[param[0]]=param[1]
    if "sort_by" in params:
        sort_by=params['sort_by']
    else:
        sort_by=None
    if 'order' in params:
        order = params['order']
    else:
        order = None
    if sort_by == 'num_of_pages':
        papers = Paper.objects.all().order_by("id")
    else:
        if order == "descending":
            papers = Paper.objects.all().order_by("-"+sort_by)
        elif order == "ascending":
            papers = Paper.objects.all().order_by(sort_by)
        else:
            papers = Paper.objects.all().order_by('id')
    if 'num_of_pages' == sort_by:
        for i,paper in enumerate(papers):
            try:
                page_idx = [int(x) for x in paper.pages.split('-')]
            except ValueError:
                pass
            if len(page_idx)==2:
                page_start = page_idx[0]
                page_end = page_idx[1]
                paper.num_of_pages = page_end - page_start + 1
            else:
                paper.num_of_pages=-1
        if order == 'descending' and not paper.num_of_pages==-1:
            papers = sorted([p for p in papers],key = lambda x:x.num_of_pages)
        elif not paper.num_of_pages==-1:
            papers =sorted([p for p in papers], key = lambda x:x.num_of_pages, reverse=True)
    for paper in papers:
        paper.color = '#FFFFFF'
        reports = paper.reports.all().order_by('id')
        paper.num_of_reports = len(reports)
        for report in reports:
            today = datetime.datetime.today()
            tdatetime = datetime.datetime.strptime(report.date, "%Y-%m-%d")
            if gakunen_subtraction(today,tdatetime) <= 3:
                paper.color="#FFBB69"
        if (not paper.reading=="") and paper.color !="#FFBB69":
            paper.color = '#FFFFCC'
        if not paper.note == '': #noteに文字列が存在する場合
            paper.color = "D3EDFB" #行を水色に設定
        try:
            page_idx = [int(x) for x in paper.pages.split("-")]
        except ValueError:
            page_idx = []
        if len(page_idx)==2:
            page_start = page_idx[0]
            page_end = page_idx[1]
            paper.num_of_pages = page_end - page_start + 1
        else:
            paper.num_of_pages=-1
    return render(request,
                  'cms/paper_list.html',
                  {'papers':papers})


def paper_edit(request, paper_id=None):
    if paper_id:
        paper = get_object_or_404(Paper, pk=paper_id)
    else:
        paper = Paper()

    if request.method == 'POST':
        form = PaperForm(request.POST, instance=paper)
        if form.is_valid():
            paper = form.save(commit=False)
            paper.save()
            return redirect('cms:paper_list')
    else:
        form = PaperForm(instance=paper)
    return render(request, 'cms/paper_edit.html', dict(form=form, paper_id=paper_id))


def admin_message(request, paper_id=None):
    papers = Paper.objects.all().order_by('id')
    return render(request,
                  'cms/admin_message.html',
                  {'papers':papers})

def paper_del(request, paper_id):
    paper = get_object_or_404(Paper, pk=paper_id)
    paper.delete()
    return redirect('cms:paper_list')



class ReportList(ListView):
    context_object_name = 'reports'
    template_name = 'cms/reports_list.html'
    paginate_by = 6
    def get(self, request, *args, **kwargs):
        paper = get_object_or_404(Paper, pk = kwargs['paper_id'])
        reports = paper.reports.all().order_by('id')
        self.object_list = reports

        context = self.get_context_data(object_list=self.object_list, paper=paper)
        return self.render_to_response(context)


def report_edit(request, paper_id, report_id=None):
    paper = get_object_or_404(Paper, pk=paper_id)
    if report_id:
        report = get_object_or_404(Report, pk=report_id)
    else:
        report = Report()

    if request.method == 'POST':
        form = ReportForm(request.POST, instance=report)
        if form.is_valid():
            report = form.save(commit=False)
            report.paper = paper
            report.save()
            return redirect('cms:report_list', paper_id=paper_id)
    else:
        form = ReportForm(instance=report)

    return render(request,
                  'cms/report_edit.html',
                  dict(form=form, paper_id=paper_id, report_id=report_id))

def report_del(request, paper_id, report_id):
    """感想の削除"""
    report = get_object_or_404(Report, pk=report_id)
    report.delete()
    return redirect('cms:report_list', paper_id=paper_id)

cms/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<title>{% block title %}Papers{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block extrahead %}{% endblock %}
</head>
<body>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
</body>
</html>

cms/templates/cms/admin_message.html
{% extends "base.html" %}

{% block title %}論文・参考書紹介システム 運用者の方へ{% endblock title %}

{% block content %}
<h2>注意</h2>
データの大幅な変更や，システムの変更を施す際には，事前にサーバ上のディレクトリ自体のバックアップを取っておくことをおすすめします．<br>
本システムはDjangoとPython以外は，paperintro/だけで完結しているため，paperintro/さえ保存していれば復元が可能です．<br>

<h2>環境構築</h2>
新たなサーバ上で本システムを構築する際の注意点を載せています．<br>
本システムは2016年現在，Ubuntu16.04上のpython3.5.2とDjangoで運用しています．<br>
djangoは2016年現在では，pipによる次のコマンドでインストールできます．<br>
sudo pip3 install django<br>
sudo pip3 install django-bootstrap-form<br>

paperintroディレクトリ内で，次のコマンドを実行すれば，本システムを起動できます．<br>
python3 manage.py runserver [IPアドレス]:[ポート]


<h2>データベース</h2>
論文・参考書のデータベースはSQLite3形式で，~/paperintro/db.sqlite3です．<br>
http://IPアドレス:ポート/admin/には論文データを管理するためのページが準備されています．<br>
SQLite3を直接操作することが難しい場合は，管理者ページから一括のデータ操作が可能となっています．<br>

<h2>その他インタフェース</h2>
HTMLに関する設定は，~/paperintro/cms/templates/cms/*.htmlで変更してください．<br>
SQLiteとのインタフェースとしてDjangoを利用しているため，データベースの構造・ソーティング機能，その他新しい機能の追加を行う際にはcms下のPythonプログラムを変更してください．<br>
{% endblock content %}

cms/templates/cms/paper_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}論文・参考書紹介用リスト{% endblock title %}

{% block content %}
    <h3 class="page-header">紹介用論文の編集</h3>
    {% if paper_id %}
    <form action="{% url 'cms:paper_mod' paper_id=paper_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <form action="{% url 'cms:paper_add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'cms:paper_list' %}" class="btn btn-default btn-sm">戻る</a>
{% endblock content %}

cms/templates/cms/paper_list.html
{% extends "base.html" %}

{% block title %}最適化数理分野 論文紹介用リスト{% endblock title %}


{% block extrahead %}
<script>
$(function() {
  $('.del_confirm').on('click', function () {
     $("#del_pk").text($(this).attr("pk"));
     $('#del_url').attr('href', $(this).attr("url"));
  });
});
</script>
<style>
table {
table-layout:fixed;
margin-top: 8px;
margin-left: 0px;
}
</style>
{% endblock %}

{% block content %}
<html leftmargin="10">
  <h3 class="page-header">論文・参考書紹介用リスト</h3>
  <p>
    過去3年間に紹介された論文は橙色に表示しています。<br>
    現在、研究室内の他のメンバーが取り組んでいる論文は黄色に表示しています。<br>
    ヘッダ行の三角マークをクリックすればソートを行います。<br>
    論文紹介に向けて勉強する際には、他のメンバーとの重複を避けるために、Control->編集->Readingに自分の名前を入れるようご協力お願いします。<br>
    <br>
  </p>
    <table class="table table-bordered" width="1380">
      <thead>
        <tr>
	  <!--<th>ID</th>-->
          <th width="150">Title<a href="?sort_by=title&order=ascending">▲</a><a href="?sort_by=title&order=descending">▼</a></th>
	  <th width="150">Authors<a href="?sort_by=authors&order=ascending">▲</a><a href="?sort_by=title&order=descending">▼</a></th>
	  <th width="150">References<a href="?sort_by=references&order=ascending">▲</a><a href="?sort_by=references&order=descending">▼</a></th>
	  <th width="80">Pages<a href="?sort_by=num_of_pages&order=ascending">▲</a><a href="?sort_by=num_of_pages&order=descending">▼</a></th>
	  <th width="80">year<a href="?sort_by=year&order=ascending">▲</a><a href="?sort_by=year&order=descending">▼</a></th>
	  <th width="600">abstract</th>
	  <th width="200">URL</th>
	  <th width="150">Reading<a href="?sort_by=reading&order=ascending">▲</a><a href="?sort_by=reading&order=descending">▼</a></th>
	  <th width="80">Note</th>
	  <th width="160">Control</th>
        </tr>
      </thead>
      <tbody>
        {% for paper in papers %}
        <tr bgcolor={{paper.color}}>
	  <!--<td>{{ paper.id }}</td>-->
          <td>{{ paper.title }}</td>
	  <td>{{ paper.authors }} </td>
	  <td>{{ paper.references }} </td>
	  <td>{{ paper.pages }}<br>{% ifnotequal paper.num_of_pages None %} ({{paper.num_of_pages}}){% endifnotequal %}</td>
	  <td>{% ifnotequal paper.year 0 %}{{ paper.year }}{% endifnotequal %}</td>
	  <td>{{ paper.abstract }}</td>
	  <td style="word-break:break-all"><a href={{ paper.URL }}>{{paper.URL}}</a></td>
	  <td>{{ paper.reading }}</td>
	  <td>{{ paper.note }}</td>
          <td>
            <a href="{% url 'cms:paper_mod' paper_id=paper.id %}" class="btn btn-default btn-sm">編集</a>
	    <button class="btn btn-default btn-sm del_confirm" data-toggle="modal" data-target="#deleteModal" pk="{{ paper.id }}" url="{% url 'cms:paper_del' paper_id=paper.id %}">削除</button>
	    <a href="{% url 'cms:report_list' paper_id=paper.id %}" class="btn btn-default btn-sm btn-primary">要約一覧 ({{ paper.num_of_reports }})</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <a href="{% url 'cms:paper_add' %}" class="btn btn-default btn-sm">論文の追加</a><br>
    <a href="{% url 'cms:admin_message'%}">管理者の方へ<a><br>
	<a href="../../admin">データ管理</a>
</html>

{# 削除を確認するモーダル ダイアログ #}
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="deleteModalLabel">確認</h4>
      </div>
      <div class="modal-body">
	<!--        <p>Reporter: <span id="del_pk"></span> を削除しますか？</p> -->
	<p>本当に削除しますか？</p>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-primary" id="del_url">OK</a>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

cms/templates/cms/report_edit.html
{% extends "base.html" %}
{% load bootstrap %}
{% block extrahead %}
 {{ form.media }}
{% endblock %}

{% block title %}論文・参考書紹介要約の編集{% endblock title %}

{% block content %}
    <h3 class="page-header">論文紹介要約の編集</h3>
    {% if report_id %}
    <form action="{% url 'cms:report_mod' paper_id=paper_id report_id=report_id %}" method="post" class="form-horizontal" role="form" onkeypress="return event.Keycode != 13;">
    {% else %}
    <form action="{% url 'cms:report_add' paper_id=paper_id %}" method="post" class="form-horizontal" role="form" onkeypress="return event.Keycode != 13;">
    {% endif %}
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'cms:report_list' paper_id=paper_id %}" class="btn btn-default btn-sm">戻る</a>
{% endblock content %}

cms/templates/cms/report_list.html
{% extends "base.html" %}

{% block title %}論文・参考書紹介要約一覧{% endblock title %}

{% block extrahead %}
<script>
$(function() {
  $('.del_confirm').on('click', function () {
     $("#del_pk").text($(this).attr("pk"));
     $('#del_url').attr('href', $(this).attr("url"));
  });
});
</script>
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
    <h3 class="page-header">論文紹介要約一覧<small>{{ paper.name }}</small></h3>
    <a href="{% url 'cms:report_add' paper_id=paper.id %}" class="btn btn-default btn-sm">追加</a>
    <table class="table table-bordered">
      <thead>
        <tr>
	  <!--          <th>ID</th>-->
	  <th>Reporter</th>
	  <th>Date</th>
	  <th>Motivations</th>
	  <th>Contributions</th>
	  <th>Questions and Future works</th>
          <th>Control</th>
        </tr>
      </thead>
      <tbody>
        {% for report in reports %}
        <tr>
	  <!--          <td>{{ report.id }}</td>-->
          <td>{{ report.reporter|linebreaksbr }}</td>
	  <td>{{ report.date|linebreaksbr }}</td>
	  <td>{{ report.motivations|linebreaksbr }}</td>
	  <td>{{ report.contributions|linebreaksbr }}</td>
	  <td>{{ report.questions|linebreaks }}</td>
          <td>
            <a href="{% url 'cms:report_mod' paper_id=paper.id report_id=report.id %}" class="btn btn-default btn-sm">編集</a>
	    <button class="btn btn-default btn-sm del_confirm" data-toggle="modal" data-target="#deleteModal" pk="{{ report.id }}" url="{% url 'cms:report_del' paper_id=paper.id report_id=report.id %}">削除</button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><a href="#">&laquo;</a></li>
      {% endif %}
      {% for linkpage in page_obj.paginator.page_range %}
        {% ifequal linkpage page_obj.number %}
          <li  class="active"><a href="#">{{ linkpage }}</a></li>
        {% else %}
          <li><a href="?page={{ linkpage }}">{{ linkpage }}</a></li>
        {% endifequal %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><a href="#">&raquo;</a></li>
      {% endif %}
    </ul>
    {% endif %}

    <div>
      <a href="{% url 'cms:paper_list' %}" class="btn btn-default btn-sm">戻る</a>
    </div>

{# 削除を確認するモーダル ダイアログ #}
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="deleteModalLabel">確認</h4>
      </div>
      <div class="modal-body">
	<!--        <p>Reporter: <span id="del_pk"></span> を削除しますか？</p> -->
	<p>本当に削除しますか？</p>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-primary" id="del_url">OK</a>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}